@extends($activeTemplate.'layouts.frontend')
@section('content')


<section class="section bg-light section-about" id="about">
                <div class="container">
                    <!-- Block @s -->
                    <div class="nk-block nk-block-about">
                        <div class="row gutter-vr-30px align-items-center pdb-l">
                            <div class="col-lg-12">
                                <div class="nk-block-text">
                                    <h2 class="title animated" data-animate="fadeInUp" data-delay=".1">Terms and Conditions</h2>
                                    <p class="animated" data-animate="fadeInUp" data-delay=".2">1.1. These terms apply to your use of the website. By accessing and using the website: a) you agree to these terms; and b) where your access and use is on behalf of another person (eg. a company), you confirm that you are authorised to, and do in fact, agree to these terms on that person’s behalf and that by agreeing to these terms on that person’s behalf that person is bound by these terms. </p>
                                    <p class="animated" data-animate="fadeInUp" data-delay=".3">1.2 If you do not agree to these terms you are not authorised to access and use the website and you must immediately stop doing so. 2. Changes 2.1. We may change these terms at any time by updating them on the website. Unless stated otherwise, any change takes effect immediately. You are responsible for ensuring you are familiar with the latest terms. By continuing to access and use the website, you agree to be bound by the changed terms.</p>
                                    <p class="animated" data-animate="fadeInUp" data-delay=".4">2.2. We may change, suspend, discontinue, or restrict access to the website without notice or liability. 2.3. These terms were last updated on 12 June 2019.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".5">3. Definitions In these terms: “including” and similar words do not imply any limit. “loss” means any direct, indirect or consequential loss including loss of profits, savings, revenue or data, and any other claim, damage, loss, liability and cost (including legal costs on a solicitor and own client basis). “personal information” means information about an identifiable living person. “terms” means these terms and conditions. “underlying system” means any network, system, software, data or material that underlies or is connected to the website. “user ID” means a unique name and/or password allocated to you, to allow access to certain parts of the website. “we”, “us” and “our” mean “Interlay”. “website” means “www.Interlay.com ”. “you” means you, or if clause 1.1b applies then both you and the other person on whose behalf you are acting.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".6">4. Your Obligations 4.1. You must provide true, current and complete information in your dealings with us (including when setting up an account), and must promptly update that information as required so that the information remains true, current, and complete. 4.2. If you are given a user ID, you must keep your user ID secure and: a) not permit any other person to use your user ID, including not disclosing or providing it to any other person; and b) immediately notify us if you become aware of any unauthorised use or disclosure of your user ID, by sending an email to admin@Interlay.com</p>

<p class="animated" data-animate="fadeInUp" data-delay=".7">4.3. You must: a) not act in a way, or use or introduce anything (including any virus, worm, Trojan horse, timebomb, keystroke logger, spyware or other similar feature) that in any way compromises, or may compromise, the website or any underlying system, or otherwise attempt to damage or interfere with the website or any underlying system; and b) unless with our agreement, access the website via standard web browsers only and not by any other method. Other methods include scraping, deep-linking, harvesting, data mining, use of a robot or spider, automation, or any similar data gathering, extraction or monitoring method. 4.4. You must obtain our written permission to establish a link to our website. If you wish to do so, email your request to admin@Interlay.com</p>

<p class="animated" data-animate="fadeInUp" data-delay=".8">4.5. You indemnify us against all loss we suffer or incur as a direct or indirect result of your failure to comply with these terms, including any failure of a person who accesses and uses our website by using your user ID. 5. Intellectual Property We own or license all propriety and intellectual property rights in the website and its contents (including all information, data, text, graphics, artwork, photographs, logos, icons, sound recordings, videos, and ‘look and feel’), and the underlying systems.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".9">6. Disclaimers 6.1. To the extent permitted by law, we and our licensors have no liability or responsibility to you or any other person for any loss in connection with: a) the website being unavailable (in whole or in part) or performing slowly; b) any error in, or omission from, any information made available through the Website; c) any exposure to viruses or other forms of interference which may damage your computer system or expose you to fraud when you access or use the Website. To avoid doubt, you are responsible for ensuring the process by which you access and use the website protects you from this; and d) any site linked from the website. Any link on the website to other sites does not imply any endorsement, approval or recommendation of, or responsibility for, those sites or their contents, operations, products or operators. 6.2. We make no representation or warranty that the Website is appropriate or available for use in all countries or that the content satisfies the laws of all countries. You are responsible for ensuring that your access to and use of the Website is not illegal or prohibited, and for your own compliance with applicable local laws.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".10">6.3. Investment Disclaimers: All returns are net of management fees, but before adviser monitoring and custodial fees. All returns are gross of all taxes. Interlay asset allocations have changed over time. All returns are based on our current asset allocation model. Returns are a combination of actual returns (where available) and simulated data. All returns have been sourced from data sources that Interlay believes are accurate. Past performance is not necessarily an indication of future performance. Interlay does not represent or warrant that such forward statements will be achieved or will prove to be correct. All financial products or securities involve risks. Individuals should obtain specific investment advice from a qualified adviser before making any investment decisions.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".11">7. Liability 7.1. To the maximum extent permitted by law: a) you access and use the website. b) we offer the best organic responsibility to you or any other person for any of your connection with these terms, with the website, or your access and use of ( every adequate ability to access or use) the website to achieve your to start Benefiting and make a Life Changing profits. This applies regardless of whether our liability or responsibility arises in contract equity, statutory duty, or otherwise.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".12">7.2. Except to the extent permitted by law, nothing in these terms has the effect of contracting out of the New Zealand Consumer Guarantees Act 1993 or any other consumer protection law that cannot be excluded. To the extent our credibility cannot be excluded but can be situated to help you achieve your goals with Company.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".13">8. Privacy Policy 8.1. You are not required to provide personal information to us, although in some cases if you choose not to do so then we will be unable to make certain sections of the website available to you. For example, we may need to have your contact information in order to provide you with updates from our website. 8.2. When you provide personal information to us, we will comply with the New Zealand Privacy Act 1993 and if applicable, the European Union’s General Data Protection Regulations.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".14">8.3. The personal information you provide to us (including any information provided if you register for an account) is collected and may be used for communicating with you, statistical analysis, the marketing by us of products and services to you, credit checks (if necessary), and research and development. 8.4. We may also collect technical information whenever you log on to, or visit the public version of, our website. This may include information about the way users arrive at, browse through and interact with our website. We may collect this type of technical information through the use of cookies and other means. Cookies are alphanumeric identifiers that we transfer to your computer’s hard drive to enable our systems to recognise your browser. If you want to disable cookies, you may do so by changing the settings on your browser. However, if you do so, you may not be able to use all the functions of the website. We use the technical information we collect to have a better understanding of the way people use our website, to improve the way it works and to personalise it to be more relevant and useful to your particular needs. We may also use this information to assist in making any advertising we display on the website more personalised and applicable to your interests.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".15">8.5. Generally, we do not disclose personal information to third parties for them to use for their own purposes. However, some of the circumstances in which we may do this are: a) to service providers and other persons working with us to make the website available or improve or develop its functionality (eg we may use a third-party supplier to host the website);.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".16">b) in relation to the proposed purchase or acquisition of our business or assets; or c) where required by applicable law or any court, or in response to a legitimate request by a law enforcement agency. 8.6. Any personal information you provide to us may be stored on the secure servers of our trusted service providers, which may be located outside New Zealand. This may involve the transfer of your personal information to countries which have less legal protection for personal information than New Zealand.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".17">8.7. You have the right to request access to and correction of any of the personal information we hold about you. If you would like to exercise these rights, please email us at admin@Interlay.com 9. Suspension and Termination 9.1. Without prejudice to any other right or remedy available to us, if we consider that you have breached these terms or we otherwise consider it appropriate, we may immediately, and without notice, suspend or terminate your access to the website (or any part of it).</p>

<p class="animated" data-animate="fadeInUp" data-delay=".18">9.2. On suspension or termination, you must immediately cease using the website and must not attempt to gain further access. 10. General 10.1. If we need to contact you, we may do so by email or by posting a notice on the website. You agree that this satisfies all legal requirements in relation to written communications. 10.2. These terms, and any dispute relating to these terms or the website, are governed by and must be interpreted in accordance with the laws of New Zealand. Each party submits to the non-exclusive jurisdiction of the courts of New Zealand in relation to any dispute connected with these terms or the website.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".19">10.3. For us to waive a right under these terms, the waiver must be in writing. 10.4. Clauses which by their nature are intended to survive termination of these terms — including clauses 4.5, 5, 6, 7 and 10.1 — continue in force. 10.5. If any part or provision of these terms is or becomes illegal, unenforceable, or invalid, then that part or provision is deemed to be modified to the extent required to remedy the illegality, unenforceability or invalidity. If a modification is not possible, the part or provision must be treated for all purposes as severed from these terms. The remainder of these terms will be binding on you.</p>

<p class="animated" data-animate="fadeInUp" data-delay=".20">10.6. Interlay. is only registered to carry on activities in New Zealand and All over the World Accessing any of service via this website is a great offer to indulge in, inducement or invitation to purchase those products or services in any other jurisdiction. 10.7. These terms set out everything agreed by the parties relating to your use of the website and supersede and cancel anything discussed, exchanged or agreed prior to you agreeing to these terms. The parties have not relied on any representation, warranty or agreement relating to the website that is not expressly set out in the terms, and no such representation, warranty or agreement has any effect from the date you agreed to these terms.</p>


                                </div>
                            </div>
                            <!--<div class="col-lg-6">-->
                            <!--    <div class="nk-block-video animated" data-animate="fadeInUp" data-delay=".5">-->
                            <!--        <img src="images/video/a.png" alt="video">-->
                            <!--        <a href="https://www.youtube.com/watch?v=SSo_EIwHSd4" class="nk-block-video-play video-popup btn-play btn-play-light"><em class="fas fa-play"></em></a>-->
                            <!--    </div>-->
                            <!--</div>-->
                        </div>
                    </div><!-- .block @e -->
                    <!-- Section Head @s -->
                    <!--<div class="section-head">-->
                    <!--    <h2 class="title title-lg animated" data-animate="fadeInUp" data-delay=".6">Key features of Coinelavate</h2>-->
                    <!--</div><!-- .section-head @e -->
                    <!-- Block @s -->
                    <!-- .block @s -->
                </div>
            </section>




@endsection